project_name: examplecli
before:
  hooks:
    - go mod download
    - go generate ./...
release:
  prerelease: false
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/thobianchi/examplecli/cmd.version={{.Version}} -X github.com/thobianchi/examplecli/cmd.commit={{.Commit}} -X github.com/thobianchi/examplecli/cmd.date={{.Date}}
signs:
  - artifacts: none

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      bit: Arm
      bitv6: Arm6
      bitv7: Arm7
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Homebrews
brews:
  - name: examplecli
    github:
      owner: thobianchi
      name: homebrew-tap
    commit_author:
      name: thobianchi
      email: thomas.bianchi8@gmail.com
    folder: Formula
    homepage: https://mia-platform.eu
    description: Example CLI
    test: |
      system "examplecli version"
